### ISSUE TITLE
Gist plugin not loading

### ISSUE THREAD

**Issue by Relequestual** [ngs-archives/gist-codaplugin#2]
Running latest coda (2.0.4) and OSX 10.6.8.
Get the following error message in console...

16/11/2012 16:00:39 Coda 2[2880]    Could not load plug-in "Gist.codaplugin" due to error:Error Domain=NSCocoaErrorDomain Code=3588 UserInfo=0x11b808590 "The bundle “Gist” couldn’t be loaded."

=[

**Comment by ngs** [comment]
Sorry, I don't have OS 10.6 environment and it does not occur for me on OS 10.7 and .8.

I will try to build test environment with 10.6 and please report me if you it occur for you in OS 10.7 or .8.

Thank you.
